version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
      - devcontainer-vscode-server:/home/vscode/.vscode-server
      - devcontainer-go-modules:/home/vscode/go
      - ./.gemini_user:/home/vscode/.gemini
    environment:
      - PYTHONPATH=/workspace
      - MIX_ENV=dev
      - GOPATH=/home/vscode/go
      - GOROOT=/usr/local/go
    ports:
      - "3000:3000"  # Python Flask/FastAPI
      - "4000:4000"  # Elixir Phoenix
      - "8000:8000"  # Rust web server
    stdin_open: true
    tty: true
    # Let the Dockerfile handle the command
    user: vscode
   
  

volumes:
  devcontainer-vscode-server:
  devcontainer-go-modules: